main: me.konicai.commandutilities.CommandUtilities
name: ${project.name}
version: ${project.version}
description: ${project.description}
author: Konicai
api-version: 1.13
commands:
  commandutil:
    description: Manage CommandUtilities
    usage: "Usage: /commandutil [ reload | get <config option> | set <config option> <value> ]"